### ISSUE TITLE
Not sure if it's my settings but can't get it to work

### ISSUE THREAD

**Issue by keirakatana** [ratwithacompiler/OBS-multitrack-stream#2]
Couldn't see a way to ask a question so doing it here. Sorry if it's not protocol.. 

So I have pretzel rocks as a source with track 2 unchecked, but the music still comes through on the vod because the source is set to 'monitor only' otherwise I don't hear it, then audio is passed through my 'desktop audio' source which doesn't have track 2 unchecked, otherwise VODS wouldn't hear my game audio. What do I do about this? Oh and btw this is a 1 pc set up and I don't use the OBS audio settings, all my audio is done through sources for max control.

**Comment by ratwithacompiler** [comment]
You need to separate the music from the desktop audio completely. On single PC on Windows that won't work without some kind of extra tool. Easiest way on is probably via Voicemeeter. You just play music with whatever program to the voicemeeter virtual audio device instead of desktop audio and set it so only you can hear that device and then just capture that with OBS as source.

**Comment by ratwithacompiler** [comment]
This is now a native feature in the OBS UI as of 26.1 RC 1 so no more need for this plugin. 

26.1: https://github.com/obsproject/obs-studio/releases
