### ISSUE TITLE
No Settings Available

### ISSUE THREAD

**Issue by bombe-atomique** [ratwithacompiler/OBS-multitrack-stream#3]
When attempting to follow the installation steps, the script settings are not visible and the message "No Settings Available" appears. Thank you for any advice you have.
![no settings avail](https://user-images.githubusercontent.com/74649122/99547850-04ee1380-2986-11eb-96ca-e5d26357883d.JPG)

**Comment by ratwithacompiler** [comment]
Looks like either your OBS isn't built with lua scripting support or there's some error when trying to load it. 

If you just use normal OBS on Windows downloaded from the OBS website or github it's probably the latter. Maybe check the OBS logs for errors and also make sure you downloaded it correctly (you want the raw lua file but sometimes people accidentally download the github html page).

Otherwise if you're not using the normal official OBS release your OBS may not have scripting support, you can try some of the sample lua scripts OBS itself comes with (it usually shows you them when you hit + to add a new one at first), if those dont work your OBS dosen't have lua scripting support.

**Comment by ratwithacompiler** [comment]
This is now a native feature in the OBS UI as of 26.1 RC 1 so no more need for this plugin. 

26.1: https://github.com/obsproject/obs-studio/releases
