### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Laimov** [ratwithacompiler/OBS-multitrack-stream#4]
the first one is the file from _installation_. If I'm not wrong, the first file worked the first day, then, after testing it multiple times next days it stopped working, I tried re-adding it, nothing happens
the second one is the _src_ file, just gives error
Am I doing something wrong?
By the way, you mentioned OBS will add a feature like this in the future update, is that true? Any way to find more info?

![Screenshot_3](https://user-images.githubusercontent.com/74740943/99725457-d7a48100-2abd-11eb-9b63-458dabf4c42d.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/74740943/99725707-29e5a200-2abe-11eb-9bbb-bb4caf530be5.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/74740943/99725304-94e2a900-2abd-11eb-98d4-47653b86b98b.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/74740943/99725302-944a1280-2abd-11eb-93d9-6b987685d479.jpg)

**Comment by ratwithacompiler** [comment]
Regarding it not working, I'm not sure if that's on the plugin side or on Twitch's side, sometimes even if everything is set up correctly twitch just doesn't seem to use it for a stream for no apparent reason and then the next it works again.

Regarding the second file error, it says `error near <` so you probably downloaded the html file instead of the raw file (click Raw top right) but the link in the download instructions should always link to the latest version.

Regarding OBS integration that's already in the master branch https://github.com/obsproject/obs-studio/commit/6b81c106d827c5a1e81fe92ac9d2e7641c061e7e so it will be included in the next OBS version whenever they release that.

**Comment by Laimov** [comment]
Aight, thanks for the info, I'll try to do some more magic, maybe it works eventually. Will leave this thread open for a couple of days.

**Comment by ratwithacompiler** [comment]
This is now a native feature in the OBS UI as of 26.1 RC 1 so no more need for this plugin. 

26.1: https://github.com/obsproject/obs-studio/releases
