### ISSUE TITLE
Music through Voicemeeter

### ISSUE THREAD

**Issue by Starknesses** [ratwithacompiler/OBS-multitrack-stream#5]
Can someone show pictures or video of this please?

- set Voicemeeter to play the music/audio from that device to your headphones and to the virtual device output
- add a OBS audio input source in OBS that uses that device as input source
- now you hear the music and OBS captures it but it's separate from desktop audio and can be separate for the VOD

I've spent an entire day trying to figure out how to have everything going through voicemeeter, but all of it is played through my headphones, which OBS picks up on track 1

Please for the love of God help. I've mixed and mastered audio for 15 years on hardware and Cubase and all of this software is the most confusing thing in the world.

**Comment by RonGeorge** [comment]
Its very confusing. I still haven't gotten it to work on Twitch's side, but I'm sure my settings are correct. This is using Voicemeeter. See if this helps.

https://i.imgur.com/3So9E6F.png

**Comment by ratwithacompiler** [comment]
Sorry didn't see that earlier but regarding setting that up with voicemeeter, it can be pretty confusing but there are a bunch tutorials on youtube on how to set up local recordings with music excluded via voicemeeter and OBS. Those should almost fully apply to this too, minus checking the VOD track setting in OBS instead of the recording track one.

This is now a native feature in the OBS UI as of 26.1 RC 1 so no more need for this plugin.
26.1: https://github.com/obsproject/obs-studio/releases
